version: '3.7'
services:
  app:
    build: .
    image: balance
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./logs:/logs
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=balance
    volumes:
      - db-data:/var/lib/postgresql/data/
volumes:
  db-data: